[package]
name = "Jupiterium"
version = "0.1.0"
authors = ["Hwang Jaeyoung <jaeyoung0909@kaist.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
